export const SET_SCREEN = 'SET_SCREEN';
export const NEW_FRAME = 'NEW_FRAME';

export const MOVE_BACKGROUND = 'MOVE_BACKGROUND';
export const SET_BACKGROUND = 'SET_BACKGROUND';
export const RELOAD_SPACESHIP_LASER = 'RELOAD_SPACESHIP_LASER';
export const START_RELOAD_SPACESHIP_LASER = 'START_RELOAD_SPACESHIP_LASER';

export const ADVANCE_PROGRESS = 'ADVANCE_PROGRESS';

export const SET_SPRITESHEET = 'SET_SPRITESHEET';

export const TOGGLE_KEY = 'TOGGLE_KEY';

export const MOVE_SPACESHIP = 'MOVE_SPACESHIP';
export const TOGGLE_MOVEMENT_SPEED = 'TOGGLE_MOVEMENT_SPEED';
export const RESET_SPACESHIP = 'RESET_SPACESHIP';

export const SHOOT = 'SHOOT';
export const MOVE_SHOOTS = 'MOVE_SHOOTS';
export const REMOVE_SHOOT = 'REMOVE_SHOOT';
export const REMOVE_ALL_SHOOTS = 'REMOVE_ALL_SHOOTS';

export const CREATE_METEOR = 'CREATE_METEOR';
export const MOVE_ENEMIES = 'MOVE_ENEMIES';
export const REMOVE_ALL_ENEMIES = 'REMOVE_ALL_ENEMIES';
export const REMOVE_ENEMY = 'REMOVE_ENEMY';

export const SET_CREDITS = 'SET_CREDITS';
export const SET_MULTIPLIER = 'SET_MULTIPLIER';
export const RESET_PLAYER = 'RESET_PLAYER';
export const SCORED = 'SCORED';

export const SET_STATUS = 'SET_STATUS';