export const SET_SCREEN = 'SET_SCREEN';
export const NEW_FRAME = 'NEW_FRAME';

export const MOVE_BACKGROUND = 'MOVE_BACKGROUND';
export const SET_BACKGROUND = 'SET_BACKGROUND';

export const ADVANCE_PROGRESS = 'ADVANCE_PROGRESS';

export const SET_SPRITESHEET = 'SET_SPRITESHEET';

export const TOGGLE_KEY = 'TOGGLE_KEY';

export const MOVE_SPACESHIP = 'MOVE_SPACESHIP';